server:
  listen: 0.0.0.0:8080
storage:
  backend:
    provider: Local
  modelPath:
    provider: ComfyUI
    root: /data/models
    modelTypeDirectory:
      StableDiffusion15: sd1.5
      StableDiffusionXl: sdxl
      PonyDiffusion: pony
      Illustrious: illustrious
      StableDiffusion30: sd3
      StableDiffusion35: sd3.5
      Flux1D: flux.1
      Flux1S: flux.1
  productPath:
    provider: Id
    base: /data/products
database:
  url: "sqlite:///data/database.db"
