server:
  listen: 127.0.0.1:8080
  cors:
    allowOrigins:
      - http://localhost:4200
storage:
  backend:
    provider: Local
  modelPath:
    provider: ComfyUI
    root: ./sample-data/models
    modelTypeDirectory:
      StableDiffusion15: sd1.5
      StableDiffusionXl: sdxl
      PonyDiffusion: pony
      Illustrious: illustrious
      StableDiffusion30: sd3
      StableDiffusion35: sd3.5
      Flux1D: flux.1
      Flux1S: flux.1
  productPath:
    provider: FileName
    base: ./sample-data/products
database:
  url: "sqlite://./sample-data/database.db"
