[package]
name = "metadata-database"
version = "0.1.0"
edition.workspace = true

[dependencies]
sea-orm.workspace = true
uuid = { version = "*", features = ["v4"] }

serde = { workspace = true, features = ["derive"] }
