//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "generated_product_model_association")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub generated_product_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_model::Entity",
        from = "Column::ModelId",
        to = "super::ai_model::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiModel,
    #[sea_orm(
        belongs_to = "super::generated_product::Entity",
        from = "Column::GeneratedProductId",
        to = "super::generated_product::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    GeneratedProduct,
}

impl Related<super::ai_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiModel.def()
    }
}

impl Related<super::generated_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedProduct.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
