//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::ai_model::Entity as AiModel;
pub use super::generated_product::Entity as GeneratedProduct;
pub use super::generated_product_model_association::Entity as GeneratedProductModelAssociation;
